import type { BoardState } from "../components/types/types";

export const STARTING_POSITION: BoardState = {
  a1: "Rook-White",
  b1: "Knight-White",
  c1: "Bishop-White",
  d1: "Queen-White",
  e1: "King-White",
  f1: "Bishop-White",
  g1: "Knight-White",
  h1: "Rook-White",
  a2: "Pawn-White",
  b2: "Pawn-White",
  c2: "Pawn-White",
  d2: "Pawn-White",
  e2: "Pawn-White",
  f2: "Pawn-White",
  g2: "Pawn-White",
  h2: "Pawn-White",

  e3: "Queen-Black",

  // Black pieces
  a8: "Rook-Black",
  b8: "Knight-Black",
  c8: "Bishop-Black",
  d8: "Queen-Black",
  e8: "King-Black",
  f8: "Bishop-Black",
  g8: "Knight-Black",
  h8: "Rook-Black",
  a7: "Pawn-Black",
  b7: "Pawn-Black",
  c7: "Pawn-Black",
  d7: "Pawn-Black",
  e7: "Pawn-Black",
  f7: "Pawn-Black",
  g7: "Pawn-Black",
  h7: "Pawn-Black",
};
